# ?? app??? ? ?? ??? default? ? ? ??
spring:
  profiles:
    active: local # default
    group:  # group?? ??
      local:
        - common
      prod:
        - common
---
# ???? ??? ???
spring:
  config:
    activate:
      on-profile: common
---
# run as local environment
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/notfound
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update  #create -> update
    show-sql: true

---
# run as prod environment
spring:
  config:
    activate:
      on-profile: prod

