# ?? app??? ? ?? ??? default? ? ? ??
spring:
  profiles:
    active: local # default
    group:  # group?? ??
      local:
        - common
      prod:
        - common
---
# ???? ??? ???
spring:
  config:
    activate:
      on-profile: common
---
# run as local environment
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/notfound
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update  #create -> update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: name,email,avatar_url
jwt:
  key: ${JWT_SECRET_KEY}  # token secret key
  access-token-expiration-minutes: 30  # access-token 만료시간
  refresh-token-expiration-minutes: 420 # refresh-token 만료시간

---
# run as prod environment
spring:
  config:
    activate:
      on-profile: prod

